<Project>

    <PropertyGroup>

        <TargetFramework>net11.0</TargetFramework>

        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <InvariantGlobalization>true</InvariantGlobalization>

        <Version>0.1.0</Version>

        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    </PropertyGroup>

</Project>
